//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPCardMaintain.EntityLayer
{
    
    
    /// <summary>
    /// Import_Log
    /// </summary>
    [Serializable()]
    [AttributeTable("Import_Log")]
    public class EntityImport_Log : Entity
    {
        
        private string _INDate;
        
        /// <summary>
        /// INDate
        /// </summary>
        public static string M_INDate = "INDate";
        
        private string _FileName;
        
        /// <summary>
        /// FileName
        /// </summary>
        public static string M_FileName = "FileName";
        
        private System.Nullable<int> _RecordNums;
        
        /// <summary>
        /// RecordNums
        /// </summary>
        public static string M_RecordNums = "RecordNums";
        
        private string _Active_Status;
        
        /// <summary>
        /// Active_Status
        /// </summary>
        public static string M_Active_Status = "Active_Status";
        
        private System.Nullable<int> _ErrorNums;
        
        /// <summary>
        /// ErrorNums
        /// </summary>
        public static string M_ErrorNums = "ErrorNums";
        
        /// <summary>
        /// INDate
        /// </summary>
        [AttributeField("INDate", "System.String", false, false, false, "String")]
        public string INDate
        {
            get
            {
                return this._INDate;
            }
            set
            {
                this._INDate = value;
            }
        }
        
        /// <summary>
        /// FileName
        /// </summary>
        [AttributeField("FileName", "System.String", false, false, false, "String")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this._FileName = value;
            }
        }
        
        /// <summary>
        /// RecordNums
        /// </summary>
        [AttributeField("RecordNums", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> RecordNums
        {
            get
            {
                return this._RecordNums;
            }
            set
            {
                this._RecordNums = value;
            }
        }
        
        /// <summary>
        /// Active_Status
        /// </summary>
        [AttributeField("Active_Status", "System.String", false, false, false, "String")]
        public string Active_Status
        {
            get
            {
                return this._Active_Status;
            }
            set
            {
                this._Active_Status = value;
            }
        }
        
        /// <summary>
        /// ErrorNums
        /// </summary>
        [AttributeField("ErrorNums", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> ErrorNums
        {
            get
            {
                return this._ErrorNums;
            }
            set
            {
                this._ErrorNums = value;
            }
        }
    }
    
    /// <summary>
    /// Import_Log
    /// </summary>
    [Serializable()]
    public class EntityImport_LogSet : EntitySet<EntityImport_Log>
    {
    }
}
