//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace CSIPCardMaintain.EntityLayer
{


    /// <summary>
    /// JOBLOG
    /// </summary>
    [Serializable()]
    [AttributeTable("JOBLOG")]
    public class EntityJOBLOG : Entity
    {

        private int _SNO;

        /// <summary>
        /// SNO
        /// </summary>
        public static string M_SNO = "SNO";

        private string _JOBNAME;

        /// <summary>
        /// JOBNAME
        /// </summary>
        public static string M_JOBNAME = "JOBNAME";

        private string _EXECBDATE;

        /// <summary>
        /// EXECBDATE
        /// </summary>
        public static string M_EXECBDATE = "EXECBDATE";

        private string _EXECBTIME;

        /// <summary>
        /// EXECBTIME
        /// </summary>
        public static string M_EXECBTIME = "EXECBTIME";

        private string _EXECEDATE;

        /// <summary>
        /// EXECEDATE
        /// </summary>
        public static string M_EXECEDATE = "EXECEDATE";

        private string _EXECETIME;

        /// <summary>
        /// EXECETIME
        /// </summary>
        public static string M_EXECETIME = "EXECETIME";

        private string _EXECUTESTATUS;

        /// <summary>
        /// EXECUTESTATUS
        /// </summary>
        public static string M_EXECUTESTATUS = "EXECUTESTATUS";

        private string _EXECMEMO;

        /// <summary>
        /// EXECMEMO
        /// </summary>
        public static string M_EXECMEMO = "EXECMEMO";

        private string _EXECUSER;

        /// <summary>
        /// EXECUSER
        /// </summary>
        public static string M_EXECUSER = "EXECUSER";

        /// <summary>
        /// SNO
        /// </summary>
        [AttributeField("SNO", "System.Int32", false, true, true, "Int32")]
        public int SNO
        {
            get
            {
                return this._SNO;
            }
            set
            {
                this._SNO = value;
            }
        }

        /// <summary>
        /// JOBNAME
        /// </summary>
        [AttributeField("JOBNAME", "System.String", false, false, false, "String")]
        public string JOBNAME
        {
            get
            {
                return this._JOBNAME;
            }
            set
            {
                this._JOBNAME = value;
            }
        }

        /// <summary>
        /// EXECBDATE
        /// </summary>
        [AttributeField("EXECBDATE", "System.String", false, false, false, "String")]
        public string EXECBDATE
        {
            get
            {
                return this._EXECBDATE;
            }
            set
            {
                this._EXECBDATE = value;
            }
        }

        /// <summary>
        /// EXECBTIME
        /// </summary>
        [AttributeField("EXECBTIME", "System.String", false, false, false, "String")]
        public string EXECBTIME
        {
            get
            {
                return this._EXECBTIME;
            }
            set
            {
                this._EXECBTIME = value;
            }
        }

        /// <summary>
        /// EXECEDATE
        /// </summary>
        [AttributeField("EXECEDATE", "System.String", false, false, false, "String")]
        public string EXECEDATE
        {
            get
            {
                return this._EXECEDATE;
            }
            set
            {
                this._EXECEDATE = value;
            }
        }

        /// <summary>
        /// EXECETIME
        /// </summary>
        [AttributeField("EXECETIME", "System.String", false, false, false, "String")]
        public string EXECETIME
        {
            get
            {
                return this._EXECETIME;
            }
            set
            {
                this._EXECETIME = value;
            }
        }

        /// <summary>
        /// EXECUTESTATUS
        /// </summary>
        [AttributeField("EXECUTESTATUS", "System.String", false, false, false, "String")]
        public string EXECUTESTATUS
        {
            get
            {
                return this._EXECUTESTATUS;
            }
            set
            {
                this._EXECUTESTATUS = value;
            }
        }

        /// <summary>
        /// EXECMEMO
        /// </summary>
        [AttributeField("EXECMEMO", "System.String", false, false, false, "String")]
        public string EXECMEMO
        {
            get
            {
                return this._EXECMEMO;
            }
            set
            {
                this._EXECMEMO = value;
            }
        }

        /// <summary>
        /// EXECUSER
        /// </summary>
        [AttributeField("EXECUSER", "System.String", false, false, false, "String")]
        public string EXECUSER
        {
            get
            {
                return this._EXECUSER;
            }
            set
            {
                this._EXECUSER = value;
            }
        }
    }

    /// <summary>
    /// JOBLOG
    /// </summary>
    [Serializable()]
    public class EntityJOBLOGSet : EntitySet<EntityJOBLOG>
    {
    }
}
